### ISSUE TITLE
Error en jekyl - ubuntu 15.10

### ISSUE THREAD

**Issue by dgomezcastro** [mathifold/mathifold_first_version#4]
Recién instalado ruby y jekyll sin errores. Parece que _posts/en/2015-09-13-cohomologia_rham.md me da un error en jekyll al llamar a 
`jekyll server --trace`
Al acceder a la página error: "Firefox can't establish a connection to the server at 127.0.0.1:4000."
A continuación la salida de terminal (actualización de git y llamada a jekyll con salida)

dgomez@dgomez-MS-7917:~$ git clone https://github.com/mathifold/mathifold.git
Cloning into 'mathifold'...
remote: Counting objects: 1138, done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 1138 (delta 53), reused 0 (delta 0), pack-reused 980
Receiving objects: 100% (1138/1138), 83.56 MiB | 1.52 MiB/s, done.
Resolving deltas: 100% (519/519), done.
Checking connectivity... done.
dgomez@dgomez-MS-7917:~$ cd mathifold
dgomez@dgomez-MS-7917:~/mathifold$ jekyll server --trace
Configuration file: /home/dgomez/mathifold/_config.yml
            Source: /home/dgomez/mathifold
       Destination: /home/dgomez/mathifold/_site
      Generating... 
  Liquid Exception: undefined method `extname' for #<Jekyll::StaticFile:0x000000025776a8> in _posts/en/2015-09-13-cohomologia_rham.md
/home/dgomez/mathifold/_plugins/mod.rb:13:in`block in get_resources': undefined method `extname' for #<Jekyll::StaticFile:0x000000025776a8> (NoMethodError)
    from /home/dgomez/mathifold/_plugins/mod.rb:9:in`each'
    from /home/dgomez/mathifold/_plugins/mod.rb:9:in `get_resources'
    from /home/dgomez/mathifold/_plugins/resource.rb:13:in`get_file'
    from /home/dgomez/mathifold/_plugins/resource.rb:68:in `render'
    from /usr/lib/ruby/vendor_ruby/liquid/block.rb:151:in`render_token'
    from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
    from /usr/lib/ruby/vendor_ruby/liquid/profiler.rb:80:in`profile_token_render'
    from /usr/lib/ruby/vendor_ruby/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
    from /usr/lib/ruby/vendor_ruby/liquid/block.rb:135:in`block in render_all'
    from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in `each'
    from /usr/lib/ruby/vendor_ruby/liquid/block.rb:122:in`render_all'
    from /usr/lib/ruby/vendor_ruby/liquid/block.rb:108:in `render'
    from /usr/lib/ruby/vendor_ruby/liquid/template.rb:210:in`block in render'
    from /usr/lib/ruby/vendor_ruby/liquid/template.rb:262:in `with_profiling'
    from /usr/lib/ruby/vendor_ruby/liquid/template.rb:209:in`render'
    from /usr/lib/ruby/vendor_ruby/liquid/template.rb:222:in `render!'
    from /usr/lib/ruby/vendor_ruby/jekyll/convertible.rb:96:in`render_liquid'
    from /usr/lib/ruby/vendor_ruby/jekyll/convertible.rb:211:in `do_layout'
    from /usr/lib/ruby/vendor_ruby/jekyll/post.rb:268:in`render'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:261:in `block in render'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:260:in`each'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:260:in `render'
    from /usr/lib/ruby/vendor_ruby/jekyll/site.rb:43:in`process'
    from /usr/lib/ruby/vendor_ruby/jekyll/command.rb:53:in `process_site'
    from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:50:in`build'
    from /usr/lib/ruby/vendor_ruby/jekyll/commands/build.rb:33:in `process'
    from /usr/lib/ruby/vendor_ruby/jekyll/commands/serve.rb:24:in`block (2 levels) in init_with_program'
    from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `call'
    from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in`block in execute'
    from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
    from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in`execute'
    from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
    from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in`program'
    from /usr/bin/jekyll:18:in `<main>'
dgomez@dgomez-MS-7917:~/mathifold$

**Comment by s-nt-s** [comment]
Que te sale si escribes `jekyll --version`?
Debería darte `jekyll 2.5.3`
